(function(){
'use strict';
var APP=document.getElementById('app');
var RECIPES=[];
var state={time:30,group:'any',sat:'any',shown:[],results:[],seed:Math.random(),rerolled:false};
var GROUPS={any:'Любой',chicken:'Курица',meat:'Мясо или фарш',fish:'Рыба и морепродукты',veg:'Без мяса'};
var SAT={any:'Неважно',hearty:'Посытнее',light:'Полегче'};
var PHOTOS={
  C01:{url:'https://images.pexels.com/photos/37107097/pexels-photo-37107097.jpeg?auto=compress&cs=tinysrgb&w=1400',alt:'Курица в медово-чесночной глазури'},
  F05:{url:'https://images.pexels.com/photos/8697543/pexels-photo-8697543.jpeg?auto=compress&cs=tinysrgb&w=1400',alt:'Креветки в чесночно-лимонном масле'},
  V09:{url:'https://images.pexels.com/photos/19217442/pexels-photo-19217442.jpeg?auto=compress&cs=tinysrgb&w=1400',alt:'Томатно-сырная паста'}
};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function track(name,props){try{var a=JSON.parse(localStorage.getItem('sv_mvp_events')||'[]');a.push({event:name,ts:new Date().toISOString(),props:props||{}});localStorage.setItem('sv_mvp_events',JSON.stringify(a.slice(-150)));}catch(e){}}
function toast(t){var e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(function(){if(e.parentNode)e.parentNode.removeChild(e);},1900);}
function groupKey(r){if(r.group==='Курица')return'chicken';if(r.group==='Мясо / фарш')return'meat';if(r.group==='Рыба / морепродукты')return'fish';return'veg';}
function emoji(r){var t=((r.title||'')+' '+(r.internal||'')).toLowerCase();if(/кревет/.test(t))return'🍤';if(/лосос|рыб|треск|минтай/.test(t))return'🐟';if(/шакш|яйц/.test(t))return'🍳';if(/нут|фасол/.test(t))return'🫘';if(/паста|спагет|лапш|орзо|лазан/.test(t))return'🍝';if(/тако|ролл|тортил/.test(t))return'🌮';if(r.group==='Курица')return'🍗';if(r.group==='Мясо / фарш')return'🥩';return'🍽️';}
function brandHeader(back){return '<header class="sv-head">'+(back?'<button class="back-btn" id="backBtn" aria-label="Назад">←</button>':'<span class="head-spacer"></span>')+'<div class="brand"><strong>Sergey<span>Voyage</span></strong><small>вкусно · понятно · без лишнего</small></div><span class="head-spacer"></span></header>';}
function selectorRow(key,label,value,icon){return '<button class="selector" data-select="'+key+'"><span class="selector-icon">'+icon+'</span><span class="selector-text"><span class="selector-label">'+label+'</span><span class="selector-value">'+esc(value)+'</span></span><span class="chev">›</span></button>';}
function renderHome(withExistingResults){APP.className='app';APP.innerHTML=brandHeader(false)+'<section class="intro"><div class="eyebrow">Быстрый подбор ужина</div><h1>Что приготовить сегодня?</h1><p>Три коротких выбора — и покажем три идеи под ваше время и настроение.</p></section><section class="picker">'+selectorRow('time','Сколько есть времени?',state.time===15?'До 15 минут':state.time===30?'До 30 минут':'До 45 минут','◷')+selectorRow('group','Что хочется приготовить?',GROUPS[state.group],'⌑')+selectorRow('sat','Какой ужин хочется?',SAT[state.sat],'♧')+'<button class="primary" id="showBtn">Показать 3 варианта <span>→</span></button><div class="trust-line"><span>36 рецептов</span><i></i><span>без регистрации</span><i></i><span>полный рецепт</span></div></section><div id="resultsZone"></div>';Array.prototype.forEach.call(document.querySelectorAll('[data-select]'),function(b){b.onclick=function(){openSheet(b.getAttribute('data-select'));};});document.getElementById('showBtn').onclick=function(){state.shown=[];state.results=[];state.rerolled=false;state.seed=Math.random();renderResults(false);};if(withExistingResults&&state.results.length)renderResultsFromArray(state.results,false);window.scrollTo(0,0);}
function openSheet(type){var title='',opts=[];if(type==='time'){title='Сколько времени есть?';opts=[['15','До 15 минут'],['30','До 30 минут'],['45','До 45 минут']];}else if(type==='group'){title='Что хочется приготовить?';opts=[['any','Любой'],['chicken','Курица'],['meat','Мясо или фарш'],['fish','Рыба и морепродукты'],['veg','Без мяса']];}else{title='Какой ужин хочется?';opts=[['any','Неважно'],['hearty','Посытнее'],['light','Полегче']];}var current=type==='time'?String(state.time):state[type];var back=document.createElement('div');back.className='sheet-backdrop';back.innerHTML='<div class="sheet"><div class="sheet-handle"></div><h3>'+title+'</h3><div class="sheet-options">'+opts.map(function(o){return '<button class="sheet-option '+(o[0]===current?'selected':'')+'" data-v="'+o[0]+'"><span>'+o[1]+'</span><b>'+(o[0]===current?'✓':'')+'</b></button>';}).join('')+'</div></div>';document.body.appendChild(back);back.onclick=function(e){if(e.target===back)back.remove();};Array.prototype.forEach.call(back.querySelectorAll('.sheet-option'),function(b){b.onclick=function(){var v=b.getAttribute('data-v');if(type==='time')state.time=Number(v);else state[type]=v;back.remove();renderHome(false);};});}
function satScore(r){if(state.sat==='any')return 0;if(state.sat==='hearty')return r.satiety==='сытный'?3:r.satiety==='универсальный'?1:0;return r.satiety==='полегче'?3:r.satiety==='универсальный'?1:0;}
function eligible(exclude){var ex={};(exclude||[]).forEach(function(x){ex[x]=1;});return RECIPES.filter(function(r){return r.active!==false&&!ex[r.id]&&Number(r.time)<=state.time&&(state.group==='any'||groupKey(r)===state.group);});}
function score(r){var n=satScore(r);if(r.one_dish)n+=.18;if(r.few_ingredients)n+=.10;if((r.active_time||99)<=15)n+=.08;if(PHOTOS[r.id])n+=state.group==='any'?1.2:.25;var h=0,s=r.id+state.seed;for(var i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return n+Math.abs(h%1000)/100000;}
function pick(n,exclude){var pool=eligible(exclude||[]);var out=[];if(state.group==='any'){var photoFirst=pool.filter(function(r){return !!PHOTOS[r.id];}).sort(function(a,b){return score(b)-score(a);});photoFirst.forEach(function(r){if(out.length<n)out.push(r);});if(out.length<n){var used={};out.forEach(function(r){used[r.id]=1;});var groups=['chicken','meat','fish','veg'];for(var gi=0;gi<groups.length&&out.length<n;gi++){var g=groups[gi],arr=pool.filter(function(r){return !used[r.id]&&groupKey(r)===g;}).sort(function(a,b){return score(b)-score(a);});if(arr[0]){out.push(arr[0]);used[arr[0].id]=1;}}if(out.length<n)pool.filter(function(r){return !used[r.id];}).sort(function(a,b){return score(b)-score(a);}).slice(0,n-out.length).forEach(function(r){out.push(r);});}return out.slice(0,n);}return pool.sort(function(a,b){return score(b)-score(a);}).slice(0,n);}
function media(r,large){var p=PHOTOS[r.id],cls=large?'recipe-photo':'card-photo';if(p)return '<div class="'+cls+' has-photo"><img src="'+esc(p.url)+'" alt="'+esc(p.alt)+'" '+(large?'':'loading="lazy"')+' onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'grid\'"><span class="photo-fallback" style="display:none">'+emoji(r)+'</span></div>';return '<div class="'+cls+' placeholder '+groupKey(r)+'"><span class="photo-fallback">'+emoji(r)+'</span></div>';}
function meta(r){var a=['<span>'+r.time+' мин</span>','<span>'+r.servings+' порц.</span>'];if(r.one_dish)a.push('<span>одна посуда</span>');else if(r.active_time<r.time)a.push('<span>активно '+r.active_time+' мин</span>');return a.join('');}
function card(r){return '<article class="food-card">'+media(r,false)+'<div class="food-card-body"><div class="card-meta">'+meta(r)+'</div><h3>'+esc(r.title)+'</h3><p>'+esc(r.internal||'')+'</p><button class="card-cta" data-open="'+esc(r.id)+'">Посмотреть рецепт <span>→</span></button></div></article>';}
function renderResults(reroll){var arr=pick(3,reroll?state.shown:[]);if(arr.length<3){var z=document.getElementById('resultsZone');if(z)z.innerHTML='<div class="notice">Не получилось собрать три варианта. Попробуйте увеличить время.</div>';return;}state.results=arr;state.shown=arr.map(function(r){return r.id;});state.rerolled=!!reroll;renderResultsFromArray(arr,reroll);track('results_view',{time:state.time,group:state.group,sat:state.sat,ids:state.shown,reroll:!!reroll});}
function renderResultsFromArray(arr,reroll){var zone=document.getElementById('resultsZone');if(!zone)return;zone.innerHTML='<section class="results"><div class="results-head"><div><div class="eyebrow">Подобрали под вас</div><h2>Три идеи на сегодня</h2></div><button class="edit-btn" id="editBtn">Изменить</button></div><div class="food-grid">'+arr.map(card).join('')+'</div>'+(eligible(state.shown).length>=3&&!reroll?'<button class="reroll" id="rerollBtn">↻ Показать другие варианты</button>':'')+'</section>';Array.prototype.forEach.call(zone.querySelectorAll('[data-open]'),function(b){b.onclick=function(){openRecipe(b.getAttribute('data-open'));};});var rr=document.getElementById('rerollBtn');if(rr)rr.onclick=function(){renderResults(true);};var ed=document.getElementById('editBtn');if(ed)ed.onclick=function(){window.scrollTo({top:0,behavior:'smooth'});};setTimeout(function(){zone.scrollIntoView({behavior:'smooth',block:'start'});},30);}
function amount(x){if(x.qty==null||x.qty==='')return esc(x.unit||'');var q=typeof x.qty==='number'&&x.qty%1!==0?String(x.qty).replace('.',','):String(x.qty);return esc(q+(x.unit?' '+x.unit:''));}
function ingredientsHtml(r){var groups={},order=[];(r.ingredients||[]).forEach(function(x){var b=x.block||'Ингредиенты';if(!groups[b]){groups[b]=[];order.push(b);}groups[b].push(x);});return order.map(function(g){return '<div class="ingredient-group-title">'+esc(g)+'</div><ul class="ingredient-list">'+groups[g].map(function(x){return '<li><span>'+esc(x.name)+(x.optional?' <em>(по желанию)</em>':'')+(x.note?'<small>'+esc(x.note)+'</small>':'')+'</span><strong>'+amount(x)+'</strong></li>';}).join('')+'</ul>';}).join('');}
function openRecipe(id){var r=null;for(var i=0;i<RECIPES.length;i++){if(RECIPES[i].id===id){r=RECIPES[i];break;}}if(!r)return;APP.className='app recipe-page';APP.innerHTML=brandHeader(true)+'<article class="recipe-shell">'+media(r,true)+'<section class="recipe-main"><div class="card-meta recipe-meta">'+meta(r)+'</div><h1>'+esc(r.title)+'</h1><p class="recipe-sub">'+esc(r.internal||'')+'</p><div class="recipe-section"><h2>Ингредиенты</h2>'+ingredientsHtml(r)+'</div><div class="recipe-section"><h2>Как приготовить</h2><div class="steps">'+(r.steps||[]).map(function(s,i){return '<div class="step"><span>'+(i+1)+'</span><p>'+esc(s)+'</p></div>';}).join('')+'</div></div><section class="offer"><div class="offer-label">Если хочется меньше ежедневных решений</div><h2>50 быстрых ужинов</h2><p>Готовая система идей на каждый день — когда не хочется снова искать, выбирать и сомневаться.</p><button id="offerBtn">Посмотреть, что внутри →</button></section></section></article>';document.getElementById('backBtn').onclick=function(){renderHome(true);};document.getElementById('offerBtn').onclick=function(){track('product_click',{recipe_id:r.id});toast('Платный продукт подключим следующим этапом');};track('recipe_open',{recipe_id:r.id});window.scrollTo(0,0);}
function load(){APP.innerHTML='<div class="loading">Загружаем рецепты…</div>';Promise.all(['recipes-chicken.json','recipes-meat.json','recipes-fish.json','recipes-veg.json'].map(function(u){return fetch(u).then(function(r){if(!r.ok)throw new Error('load');return r.json();});})).then(function(parts){RECIPES=[].concat.apply([],parts);renderHome(false);}).catch(function(){APP.innerHTML='<div class="notice"><strong>Не удалось загрузить рецепты</strong><br>Обновите страницу ещё раз.</div>';});}
load();
})();