(function(){
'use strict';
var APP=document.getElementById('app');
var GROUP_LABELS={chicken:'Курица',meat:'Мясо / фарш',fish:'Рыба / морепродукты',veg:'Без мяса'};
var GROUP_TITLES={chicken:'курица',meat:'мясо или фарш',fish:'рыба и морепродукты',veg:'без мяса'};
var PHOTO_MAP={
  C01:{url:'https://images.pexels.com/photos/37107097/pexels-photo-37107097.jpeg?auto=compress&cs=tinysrgb&w=1400',alt:'Курица в медово-чесночной глазури'},
  F05:{url:'https://images.pexels.com/photos/8697543/pexels-photo-8697543.jpeg?auto=compress&cs=tinysrgb&w=1400',alt:'Креветки в чесночно-лимонном масле'},
  V09:{url:'https://images.pexels.com/photos/19217442/pexels-photo-19217442.jpeg?auto=compress&cs=tinysrgb&w=1400',alt:'Томатно-сырная паста с моцареллой'}
};
var state={step:0,time:30,group:'any',sat:'any',shownIds:[],results:[],rerolled:false,seed:Math.random()};
var RECIPES=[];
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function top(right){return '<header class="top"><div class="logo">Sergey<b>Voyage</b></div><div class="muted">'+esc(right||'')+'</div></header>';}
function params(){var p={};try{var q=new URLSearchParams(location.search);q.forEach(function(v,k){if(/^utm_|^(content_id|keyword|campaign|source)$/.test(k))p[k]=v;});}catch(e){}return p;}
function sid(){try{var k='sv_session_id',v=sessionStorage.getItem(k);if(!v){v=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);sessionStorage.setItem(k,v);}return v;}catch(e){return 'session';}}
function track(name,props){try{var item={event:name,ts:new Date().toISOString(),session_id:sid(),page:location.pathname,source:params(),props:props||{}};var a=JSON.parse(localStorage.getItem('sv_mvp_events')||'[]');a.push(item);if(a.length>120)a=a.slice(-120);localStorage.setItem('sv_mvp_events',JSON.stringify(a));}catch(e){}}
function toast(msg){var old=document.querySelector('.toast');if(old)old.remove();var d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(function(){if(d.parentNode)d.parentNode.removeChild(d);},2300);}
function byId(id){for(var i=0;i<RECIPES.length;i++)if(RECIPES[i].id===id)return RECIPES[i];return null;}
function groupSlug(r){if(r.group==='Курица')return 'chicken';if(r.group==='Мясо / фарш')return 'meat';if(r.group==='Рыба / морепродукты')return 'fish';return 'veg';}
function visualClass(r){var s=groupSlug(r);return s==='meat'?'meat':s==='fish'?'fish':s==='veg'?'veg':'';}
function emoji(r){var t=((r.title||'')+' '+(r.internal||'')).toLowerCase();if(t.indexOf('кревет')>=0)return '🍤';if(/лосос|рыб|треск|минтай/.test(t))return '🐟';if(/шакш|яйц/.test(t))return '🍳';if(/фасол|нут/.test(t))return '🫘';if(/паста|спагет|лапш|орзо|лазан/.test(t))return '🍝';if(/тако|ролл|тортил/.test(t))return '🌮';if(r.group==='Курица')return '🍗';if(r.group==='Мясо / фарш')return '🥩';return '🍽️';}
function photoVisual(r,large){var p=PHOTO_MAP[r.id],cls=large?'recipeVisual':'visual';var idBadge=large?'':'<span class="rid">'+esc(r.id)+'</span>';if(!p)return '<div class="'+cls+' '+visualClass(r)+'">'+idBadge+'<span class="foodEmoji">'+emoji(r)+'</span></div>';return '<div class="'+cls+' '+visualClass(r)+' hasPhoto" style="overflow:hidden">'+idBadge+'<img class="foodImage" src="'+esc(p.url)+'" alt="'+esc(p.alt)+'" loading="'+(large?'eager':'lazy')+'" style="grid-area:1/1;width:100%;height:100%;object-fit:cover;display:block" onload="this.nextElementSibling.style.display=\'none\'" onerror="this.style.display=\'none\'"><span class="foodEmoji" style="grid-area:1/1">'+emoji(r)+'</span></div>';}
function satScore(r){if(state.sat==='any')return 0;var s=r.satiety;if(state.sat==='hearty')return s==='сытный'?3:(s==='универсальный'?1.5:0);return s==='полегче'?3:(s==='универсальный'?1.5:0);}
function convenienceScore(r){var x=0;if(r.one_dish)x+=0.18;if(r.few_ingredients)x+=0.10;if((r.active_time||99)<=15)x+=0.08;return x;}
function typeKey(r){var t=((r.title||'')+' '+(r.internal||'')).toLowerCase();if(/паста|спагет|лапш|орзо|лазан/.test(t))return 'pasta';if(/тако|ролл|леп[её]ш|тортил/.test(t))return 'wrap';if(/боул|рис/.test(t))return 'bowl';if(/суп/.test(t))return 'soup';if(/тефтел|котлет/.test(t))return 'balls';if(/стейк/.test(t))return 'steak';return (r.subgroup||r.method||'other').split('/')[0].trim();}
function hashTie(id){var n=0,s=id+':'+state.seed;for(var i=0;i<s.length;i++)n=((n<<5)-n+s.charCodeAt(i))|0;return Math.abs(n%1000)/100000;}
function eligible(exclude){var ex={};(exclude||[]).forEach(function(x){ex[x]=1;});return RECIPES.filter(function(r){return r.active!==false&&!ex[r.id]&&Number(r.time)<=state.time&&(state.group==='any'||r.group===GROUP_LABELS[state.group]);});}
function baseScore(r){return satScore(r)+convenienceScore(r)+hashTie(r.id);}
function pickExplicit(pool,n){var chosen=[],left=pool.slice();while(chosen.length<n&&left.length){var bestIndex=0,best=-999;for(var i=0;i<left.length;i++){var r=left[i],score=baseScore(r),tk=typeKey(r);for(var j=0;j<chosen.length;j++){if(typeKey(chosen[j])===tk)score-=0.55;if((chosen[j].method||'')===(r.method||''))score-=0.15;}if(score>best){best=score;bestIndex=i;}}chosen.push(left.splice(bestIndex,1)[0]);}return chosen;}
function pickAny(pool,n){var groups=['Курица','Мясо / фарш','Рыба / морепродукты','Без мяса'];var rot=Math.floor(state.seed*groups.length)%groups.length;groups=groups.slice(rot).concat(groups.slice(0,rot));var buckets={};groups.forEach(function(g){buckets[g]=pool.filter(function(r){return r.group===g;}).sort(function(a,b){return baseScore(b)-baseScore(a);});});var ranked=groups.filter(function(g){return buckets[g].length;}).sort(function(a,b){return baseScore(buckets[b][0])-baseScore(buckets[a][0]);});var out=[];for(var i=0;i<ranked.length&&out.length<n;i++)out.push(buckets[ranked[i]][0]);if(out.length<n){var used={};out.forEach(function(r){used[r.id]=1;});out=out.concat(pickExplicit(pool.filter(function(r){return !used[r.id];}),n-out.length));}return out.slice(0,n);}
function selectRecipes(exclude){var pool=eligible(exclude||[]);return state.group==='any'?pickAny(pool,3):pickExplicit(pool,3);}
function canReroll(){return !state.rerolled&&eligible(state.shownIds).length>=3;}
function formatAmount(x){var q=x.qty,u=x.unit||'';if(q==null||q==='')return esc(u);var val=(typeof q==='number'&&q%1!==0)?String(q).replace('.',','):String(q);return esc(val+(u?' '+u:''));}
function groupIngredients(r){var order=[],m={};(r.ingredients||[]).forEach(function(x){var b=x.block||'Ингредиенты';if(!m[b]){m[b]=[];order.push(b);}m[b].push(x);});return order.map(function(b){return '<h4>'+esc(b)+'</h4><ul class="ingredients">'+m[b].map(function(x){return '<li><span class="ingredientName">'+esc(x.name)+(x.optional?' <span class="muted">(по желанию)</span>':'')+(x.note?'<small class="ingredientNote">'+esc(x.note)+'</small>':'')+'</span><span class="amount">'+formatAmount(x)+'</span></li>';}).join('')+'</ul>';}).join('');}
function home(){state.step=0;state.shownIds=[];state.results=[];state.rerolled=false;APP.innerHTML=top('')+'<div class="eyebrow">● Подбор ужина</div><h1>Что приготовить сегодня?</h1><p class="lead">Три коротких вопроса — и получите три идеи ужина под ваше время и настроение.</p><div class="chips"><span class="chip">36 рецептов</span><span class="chip">без регистрации</span><span class="chip">быстрый выбор</span></div><div class="hero"><div class="heroDish">🍽️</div><p>Не ещё один список рецептов. А быстрый ответ на вопрос, который возникает каждый вечер.</p></div><button class="btn primary" id="start">Подобрать ужин</button>';document.getElementById('start').onclick=function(){state.step=1;track('quiz_start');question();};window.scrollTo(0,0);}
function question(){var title,lead,opts;if(state.step===1){title='Сколько есть времени?';lead='Считаем честное общее время приготовления с нуля.';opts=[['15','До 15 минут','Когда нужно максимально быстро'],['30','До 30 минут','Самый универсальный вариант'],['45','До 45 минут','Можно чуть спокойнее']];}else if(state.step===2){title='Что хочется приготовить?';lead='Выберите продукт или оставьте выбор нам.';opts=[['chicken','Курица',''],['meat','Мясо или фарш',''],['fish','Рыба и морепродукты',''],['veg','Без мяса',''],['any','Неважно','Покажем разные категории']];}else{title='Какой ужин хочется?';lead='Это мягкое предпочтение: хороший вариант не исчезнет только из-за одного тега.';opts=[['hearty','Посытнее','Паста, рис, сыр, насыщенные блюда'],['light','Полегче','Поднимем более лёгкие варианты выше'],['any','Неважно','Не будем ограничивать выбор']];}
APP.innerHTML=top('Вопрос '+state.step+' из 3')+'<button class="back" id="back">← Назад</button><div class="progress"><i style="width:'+(state.step/3*100)+'%"></i></div><div class="eyebrow">Быстрый выбор</div><h2>'+title+'</h2><p class="lead">'+lead+'</p><div class="options">'+opts.map(function(o){return '<button class="option" data-v="'+o[0]+'"><span><strong>'+o[1]+'</strong>'+(o[2]?'<small>'+o[2]+'</small>':'')+'</span><span class="arrow">→</span></button>';}).join('')+'</div>';
document.getElementById('back').onclick=function(){if(state.step===1)home();else{state.step--;question();}};Array.prototype.forEach.call(document.querySelectorAll('.option'),function(b){b.onclick=function(){var v=b.getAttribute('data-v');if(state.step===1)state.time=Number(v);if(state.step===2)state.group=v;if(state.step===3)state.sat=v;track('quiz_answer',{step:state.step,value:v});if(state.step<3){state.step++;question();}else{state.rerolled=false;showResults(false);}};});window.scrollTo(0,0);}
function resultCard(r){var badges=['<span>'+r.time+' мин</span>','<span>'+r.servings+' порц.</span>'];if(r.one_dish)badges.push('<span>одна посуда</span>');else if(r.active_time<r.time-8)badges.push('<span>активно '+r.active_time+' мин</span>');return '<article class="card">'+photoVisual(r,false)+'<div class="body"><h3>'+esc(r.title)+'</h3><div class="meta">'+badges.join('')+'</div><button class="btn primary open" data-id="'+esc(r.id)+'">Посмотреть рецепт</button></div></article>';}
function showResults(isReroll){var arr=selectRecipes(isReroll?state.shownIds:[]);if(arr.length<3){APP.innerHTML=top('')+'<div class="error"><h2>Не удалось собрать три варианта</h2><p>Попробуйте изменить время или продукт.</p><button class="btn primary" id="retry">Изменить ответы</button></div>';document.getElementById('retry').onclick=function(){state.step=1;question();};return;}state.results=arr;state.shownIds=arr.map(function(r){return r.id;});var satLabel=state.sat==='hearty'?'посытнее':state.sat==='light'?'полегче':'без ограничений';var groupLabel=state.group==='any'?'разные продукты':GROUP_TITLES[state.group];APP.innerHTML=top('Ваши 3 варианта')+'<button class="back" id="edit">← Изменить ответы</button><div class="eyebrow">Подобрали под вас</div><h2>Вот что можно приготовить сегодня</h2><div class="summary"><span>до '+state.time+' минут</span><span>'+esc(groupLabel)+'</span><span>'+satLabel+'</span></div><div class="cards">'+arr.map(resultCard).join('')+'</div><div class="actions">'+(canReroll()?'<button class="btn secondary" id="again">Хочу другие варианты</button>':'')+'<button class="btn ghost" id="restart">Начать заново</button></div><p class="note">Время и продукт — строгие условия. «Посытнее / полегче» влияет на порядок выдачи, а не отсекает рецепты жёстко.</p>';track('results_view',{time:state.time,group:state.group,satiety:state.sat,recipe_ids:state.shownIds,reroll:!!isReroll});document.getElementById('edit').onclick=function(){state.step=1;state.shownIds=[];state.results=[];state.rerolled=false;question();};document.getElementById('restart').onclick=home;var again=document.getElementById('again');if(again)again.onclick=function(){state.rerolled=true;track('reroll',{previous_ids:state.shownIds.slice()});showResults(true);};Array.prototype.forEach.call(document.querySelectorAll('.open'),function(b){b.onclick=function(){openRecipe(b.getAttribute('data-id'));};});window.scrollTo(0,0);}
function openRecipe(id){var r=byId(id);if(!r)return;track('recipe_open',{recipe_id:id});var meta=['<span>'+r.time+' мин</span>','<span>'+r.servings+' порц.</span>'];if(r.active_time<r.time)meta.push('<span>активно '+r.active_time+' мин</span>');if(r.one_dish)meta.push('<span>одна посуда</span>');APP.innerHTML=top('Рецепт')+'<button class="back" id="backResults">← К трём вариантам</button>'+photoVisual(r,true)+'<div class="recipeHead"><div class="eyebrow" style="color:#E6D9C2">Сегодня на ужин</div><h1>'+esc(r.title)+'</h1><div class="meta">'+meta.join('')+'</div></div><section class="section"><h3>Ингредиенты</h3>'+groupIngredients(r)+'</section><section class="section"><h3>Как приготовить</h3><ol class="steps">'+(r.steps||[]).map(function(s){return '<li>'+esc(s)+'</li>';}).join('')+'</ol></section><section class="offer"><div class="eyebrow" style="color:#E6D9C2">Когда не хочется выбирать каждый вечер</div><h3>50 быстрых ужинов</h3><p>Не ещё 50 случайных рецептов, а готовая система идей для обычных будней — чтобы тратить меньше времени на ежедневный выбор.</p><button class="btn" id="offerBtn">Посмотреть, что внутри</button></section><div class="actions"><button class="btn ghost" id="restartFromRecipe">Новый подбор</button></div>';document.getElementById('backResults').onclick=function(){renderStoredResults();};document.getElementById('restartFromRecipe').onclick=home;document.getElementById('offerBtn').onclick=function(){track('product_click',{recipe_id:r.id,product:'50_fast_dinners'});toast('Экран продукта подключим следующим этапом.');};window.scrollTo(0,0);}
function renderStoredResults(){if(!state.results.length){showResults(false);return;}var arr=state.results;var satLabel=state.sat==='hearty'?'посытнее':state.sat==='light'?'полегче':'без ограничений';var groupLabel=state.group==='any'?'разные продукты':GROUP_TITLES[state.group];APP.innerHTML=top('Ваши 3 варианта')+'<button class="back" id="edit">← Изменить ответы</button><div class="eyebrow">Подобрали под вас</div><h2>Вот что можно приготовить сегодня</h2><div class="summary"><span>до '+state.time+' минут</span><span>'+esc(groupLabel)+'</span><span>'+satLabel+'</span></div><div class="cards">'+arr.map(resultCard).join('')+'</div><div class="actions"><button class="btn ghost" id="restart">Начать заново</button></div>';document.getElementById('edit').onclick=function(){state.step=1;question();};document.getElementById('restart').onclick=home;Array.prototype.forEach.call(document.querySelectorAll('.open'),function(b){b.onclick=function(){openRecipe(b.getAttribute('data-id'));};});window.scrollTo(0,0);}
function init(){Promise.all(['recipes-chicken.json','recipes-meat.json','recipes-fish.json','recipes-veg.json'].map(function(u){return fetch(u,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(u+' '+r.status);return r.json();});})).then(function(parts){RECIPES=[].concat.apply([],parts);home();}).catch(function(err){APP.innerHTML=top('')+'<div class="error"><h2>Не удалось загрузить рецепты</h2><p>Обновите страницу. Если ошибка повторится, сообщите нам.</p><code>'+esc(err.message||err)+'</code></div>';});}
init();
})();
